### ISSUE TITLE
Feature request to set Java library path as part of the conf

### ISSUE THREAD

**Issue by iskakaushik** [palantir/go-java-launcher#5]
There are several ways to do this and one might argue that we could just set the "java.library.path" system property. As the library path is ordered it would be great if we could set it like so:

```
javaLibPath:
  - './agent/lib/'
  - './wrapper/lib/so/'
```

Happy to submit a PR. Thoughts?

**Comment by uschi2000** [comment]
Would you prefer an explicit option over using `-Djava.library.path`?

**Comment by iskakaushik** [comment]
I can see that argument getting super long over time. If it's not too big of a lift, i'd prefer an explicit option.

**Comment by uschi2000** [comment]
My only hesitation is that those arguments are redundant and the semantics depends on some implicit ordering. for instance:

```
javaLibPath:
  - 'foo'
jvmOpts:
  - '-Djava.library.path=bar'
```

Who wins?

**Comment by iskakaushik** [comment]
I would suggest the following semantics:

name the key "javaAdditionalLibPath" or a similar thing.
This would append to "java.library.path" if its specified as a jvm option,
else just use the list.

**Comment by uschi2000** [comment]
I would prefer to defer such a feature until the `jvmOpts` route proves too inefficient/brittle.
